# Generated by Django 5.1.7 on 2025-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('Ariary', 'Ariary'), ('Euro', 'Euro'), ('Dollars', 'Dollars')], default='Euro', max_length=10),
        ),
    ]
