# Generated by Django 5.1.7 on 2025-04-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='investor',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Portefeuille'), ('card', 'Carte'), ('bank', 'Virement bancaire')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20),
        ),
    ]
