# Generated by Django 5.1.7 on 2025-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
