# Generated by Django 5.1.7 on 2025-04-11 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_investment_commission_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_transaction', to='investments.transaction'),
        ),
    ]
