# Generated by Django 5.1.7 on 2025-04-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_moderated",
            field=models.BooleanField(default=True),
        ),
    ]
