# Generated by Django 5.1.7 on 2025-04-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_comment_is_moderated"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_reported",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_moderated",
            field=models.BooleanField(default=False),
        ),
    ]
