# Generated by Django 5.1.7 on 2025-04-11 15:30

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MGA', 'Ariary Malgache'), ('USD', 'Dollar US'), ('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
    ]
