# Generated by Django 5.1.7 on 2025-04-11 17:09

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_balance_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('MGA', 'Ariary Malgache'), ('USD', 'Dollar US'), ('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=12),
        ),
    ]
